version: "3.8"
services:
    woven:
        build:
            context: .
            dockerfile: Dockerfile
        image: '${APP_ENV}-${APP_NAME}-fpm'
        container_name: '${APP_ENV}-${APP_NAME}-fpm'
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - '8000:8000'
        depends_on:
            - mariadb

    mariadb:
        image: 'mariadb:10.11.9'
        platform: linux/arm64/v8
        container_name: '${APP_ENV}-${APP_NAME}-mariadb'
        ports:
            - '3307:3306'
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - 'mariadb:/var/lib/mysql'

volumes:
    mariadb: ~
